apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coredns-operator
rules:
# primary resources
- apiGroups:
  - addons.k8s.io
  resources:
  - coredns
  verbs:
  - '*'
# secondary resources
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  - events
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
# monitoring
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
# self
- apiGroups:
  - apps
  resourceNames:
  - coredns-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
# leader-election
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - coredns-operator-lock
  resources:
  - configmaps
  verbs:
  - '*'
