
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - discovery.addons.x-k8s.io
  resources:
  - addons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.addons.x-k8s.io
  resources:
  - addons/status
  verbs:
  - get
  - patch
  - update
